### ISSUE TITLE
Initial data generation

### ISSUE THREAD

**Issue by ShaynAli** [ShaynAli/Aipen#8]
Write a data generation module capable of generating simple bits of data, e.g. random, linear with noise

**Comment by ShaynAli** [comment]
Initially let's do random data and linear data with adjustable noise, plus anything else you guys find relevant

**Comment by rsharma1996** [comment]
Statistical noise is unexplained variability within a data sample. The term noise, in this context, came from signal processing where it was used to refer to unwanted electrical or electromagnetic energy that degrades the quality of signals and data.

**Comment by rsharma1996** [comment]
Need a module for this
